<?php

declare(strict_types=1);

namespace App\Helpdesk\BaseLinker\Marketplace\DTO;

/**
 * TODO: this data model can be simplified by adding DTOs or value objects
 */
readonly class Order
{
    /**
     * @param array<OrderProduct> $products
     */
    public function __construct(
        public int $orderId,
        public int $shopOrderId,
        public string $externalOrderId,
        public string $orderSource,
        public int $orderSourceId,
        public string $orderSourceInfo,
        public int $orderStatusId,
        public bool $confirmed,
        public int $dateConfirmed,
        public int $dateAdd,
        public int $dateInStatus,
        public string $userLogin,
        public string $phone,
        public string $email,
        public string $userComments,
        public string $adminComments,
        public string $currency,
        public string $paymentMethod,
        public string $paymentMethodCod,
        public float $paymentDone,
        public int $deliveryMethodId,
        public string $deliveryMethod,
        public float $deliveryPrice,
        public string $deliveryPackageModule,
        public string $deliveryPackageNr,
        public string $deliveryFullName,
        public string $deliveryCompany,
        public string $deliveryAddress,
        public string $deliveryCity,
        public string $deliveryState,
        public string $deliveryPostcode,
        public string $deliveryCountryCode,
        public string $deliveryPointId,
        public string $deliveryPointName,
        public string $deliveryPointAddress,
        public string $deliveryPointPostcode,
        public string $deliveryPointCity,
        public string $invoiceFullName,
        public string $invoiceCompany,
        public string $invoiceNip,
        public string $invoiceAddress,
        public string $invoiceCity,
        public string $invoiceState,
        public string $invoicePostcode,
        public string $invoiceCountryCode,
        public string $wantInvoice,
        public string $extraField1,
        public string $extraField2,
        public string $orderPage,
        public int $pickState,
        public int $packState,
        public string $deliveryCountry,
        public string $invoiceCountry,
        public array $products,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            orderId: $data['order_id'],
            shopOrderId: $data['shop_order_id'],
            externalOrderId: $data['external_order_id'],
            orderSource: $data['order_source'],
            orderSourceId: $data['order_source_id'],
            orderSourceInfo: $data['order_source_info'],
            orderStatusId: $data['order_status_id'],
            confirmed: $data['confirmed'],
            dateConfirmed: $data['date_confirmed'],
            dateAdd: $data['date_add'],
            dateInStatus: $data['date_in_status'],
            userLogin: $data['user_login'],
            phone: $data['phone'],
            email: $data['email'],
            userComments: $data['user_comments'],
            adminComments: $data['admin_comments'],
            currency: $data['currency'],
            paymentMethod: $data['payment_method'],
            paymentMethodCod: $data['payment_method_cod'],
            paymentDone: (float) $data['payment_done'],
            deliveryMethodId: $data['delivery_method_id'],
            deliveryMethod: $data['delivery_method'],
            deliveryPrice: (float) $data['delivery_price'],
            deliveryPackageModule: $data['delivery_package_module'],
            deliveryPackageNr: $data['delivery_package_nr'],
            deliveryFullName: $data['delivery_fullname'],
            deliveryCompany: $data['delivery_company'],
            deliveryAddress: $data['delivery_address'],
            deliveryCity: $data['delivery_city'],
            deliveryState: $data['delivery_state'],
            deliveryPostcode: $data['delivery_postcode'],
            deliveryCountryCode: $data['delivery_country_code'],
            deliveryPointId: $data['delivery_point_id'],
            deliveryPointName: $data['delivery_point_name'],
            deliveryPointAddress: $data['delivery_point_address'],
            deliveryPointPostcode: $data['delivery_point_postcode'],
            deliveryPointCity: $data['delivery_point_city'],
            invoiceFullName: $data['invoice_fullname'],
            invoiceCompany: $data['invoice_company'],
            invoiceNip: $data['invoice_nip'],
            invoiceAddress: $data['invoice_address'],
            invoiceCity: $data['invoice_city'],
            invoiceState: $data['invoice_state'],
            invoicePostcode: $data['invoice_postcode'],
            invoiceCountryCode: $data['invoice_country_code'],
            wantInvoice: $data['want_invoice'],
            extraField1: $data['extra_field_1'],
            extraField2: $data['extra_field_2'],
            orderPage: $data['order_page'],
            pickState: $data['pick_state'],
            packState: $data['pack_state'],
            deliveryCountry: $data['delivery_country'],
            invoiceCountry: $data['invoice_country'],
            products: array_map(OrderProduct::fromArray(...), $data['products']),
        );
    }
}
